# Generated by Django 5.2.4 on 2025-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_comment_user_fio_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.CharField(max_length=250, null=True, verbose_name='Fio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
