# Generated by Django 5.2.4 on 2025-08-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="StartMailing")),
                ("end", models.DateTimeField(verbose_name="EndMailing")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("ended", "Ended"),
                            ("running", "Running"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=250, verbose_name="Subject")),
                ("body", models.TextField(verbose_name="Body")),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=250, unique=True, verbose_name="Email"),
                ),
                ("fio", models.CharField(max_length=250, verbose_name="Fio")),
                ("comment", models.TextField(verbose_name="Comment")),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Mailing date"),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Status"),
                ),
                (
                    "email",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Email"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ServerResponse",
                    ),
                ),
            ],
        ),
    ]
