# Generated by Django 5.2.4 on 2025-08-05 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='Email')),
                ('fio', models.CharField(max_length=250, verbose_name='Fio')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='StartSending')),
                ('end', models.DateTimeField(verbose_name='EndSending')),
                ('status', models.CharField(default='Создана', max_length=50, verbose_name='Status')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Message', to='mailing.message')),
                ('recipients', models.ManyToManyField(related_name='Recipients', to='mailing.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Sending date')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('response', models.TextField(max_length=50, verbose_name='ServerResponse')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MailingList', to='mailing.mailinglist')),
            ],
        ),
    ]
